obstacle_range: 4.5
raytrace_range: 3.0
robot_radius: 0.585
inflation_radius: 0.3
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0.3}
